name: Deploy
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh with multiple commands
        uses: appleboy/ssh-action@master
        with:
          debug: true
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: sh /home/olore/apps/movies-with-friends/scripts/update.sh
