name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
    - run: npm run regression:run
      continue-on-error: true
    - name: Archive Cypress Snapshots
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: cypress/snapshots/
      env:
        CI: true
